// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authz/v1/options.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthLevel declares the authentication and exposure policy for an RPC.
type AuthLevel int32

const (
	// AUTH_LEVEL_UNSPECIFIED is intentionally fail-closed and is handled as
	// AUTH_LEVEL_AUTHENTICATED by protoc-gen-authz-go.
	AuthLevel_AUTH_LEVEL_UNSPECIFIED AuthLevel = 0
	// AUTH_LEVEL_PUBLIC permits unauthenticated requests.
	AuthLevel_AUTH_LEVEL_PUBLIC AuthLevel = 1
	// AUTH_LEVEL_AUTHENTICATED requires an internal JWT.
	AuthLevel_AUTH_LEVEL_AUTHENTICATED AuthLevel = 2
	// AUTH_LEVEL_INTERNAL is for service-to-service RPCs and must not be
	// exposed externally by a gateway.
	AuthLevel_AUTH_LEVEL_INTERNAL AuthLevel = 3
)

// Enum value maps for AuthLevel.
var (
	AuthLevel_name = map[int32]string{
		0: "AUTH_LEVEL_UNSPECIFIED",
		1: "AUTH_LEVEL_PUBLIC",
		2: "AUTH_LEVEL_AUTHENTICATED",
		3: "AUTH_LEVEL_INTERNAL",
	}
	AuthLevel_value = map[string]int32{
		"AUTH_LEVEL_UNSPECIFIED":   0,
		"AUTH_LEVEL_PUBLIC":        1,
		"AUTH_LEVEL_AUTHENTICATED": 2,
		"AUTH_LEVEL_INTERNAL":      3,
	}
)

func (x AuthLevel) Enum() *AuthLevel {
	p := new(AuthLevel)
	*p = x
	return p
}

func (x AuthLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_authz_v1_options_proto_enumTypes[0].Descriptor()
}

func (AuthLevel) Type() protoreflect.EnumType {
	return &file_authz_v1_options_proto_enumTypes[0]
}

func (x AuthLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthLevel.Descriptor instead.
func (AuthLevel) EnumDescriptor() ([]byte, []int) {
	return file_authz_v1_options_proto_rawDescGZIP(), []int{0}
}

// AuthPolicy is an authorization policy that may be associated with an RPC or
// a service. A method-level policy takes precedence over its service policy.
// required_scopes is intentionally declarative: a verifier decides how scopes
// are represented and enforced.
type AuthPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          AuthLevel              `protobuf:"varint,1,opt,name=level,proto3,enum=authz.v1.AuthLevel" json:"level,omitempty"`
	RequiredScopes []string               `protobuf:"bytes,2,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthPolicy) Reset() {
	*x = AuthPolicy{}
	mi := &file_authz_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPolicy) ProtoMessage() {}

func (x *AuthPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPolicy.ProtoReflect.Descriptor instead.
func (*AuthPolicy) Descriptor() ([]byte, []int) {
	return file_authz_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *AuthPolicy) GetLevel() AuthLevel {
	if x != nil {
		return x.Level
	}
	return AuthLevel_AUTH_LEVEL_UNSPECIFIED
}

func (x *AuthPolicy) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

var file_authz_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50002,
		Name:          "authz.v1.authz_proto_version",
		Tag:           "varint,50002,opt,name=authz_proto_version",
		Filename:      "authz/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthPolicy)(nil),
		Field:         50001,
		Name:          "authz.v1.auth_policy",
		Tag:           "bytes,50001,opt,name=auth_policy",
		Filename:      "authz/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*AuthPolicy)(nil),
		Field:         50001,
		Name:          "authz.v1.service_auth_policy",
		Tag:           "bytes,50001,opt,name=service_auth_policy",
		Filename:      "authz/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional uint32 authz_proto_version = 50002;
	E_AuthzProtoVersion = &file_authz_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional authz.v1.AuthPolicy auth_policy = 50001;
	E_AuthPolicy = &file_authz_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional authz.v1.AuthPolicy service_auth_policy = 50001;
	E_ServiceAuthPolicy = &file_authz_v1_options_proto_extTypes[2]
)

var File_authz_v1_options_proto protoreflect.FileDescriptor

const file_authz_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x16authz/v1/options.proto\x12\bauthz.v1\x1a google/protobuf/descriptor.proto\"`\n" +
	"\n" +
	"AuthPolicy\x12)\n" +
	"\x05level\x18\x01 \x01(\x0e2\x13.authz.v1.AuthLevelR\x05level\x12'\n" +
	"\x0frequired_scopes\x18\x02 \x03(\tR\x0erequiredScopes*u\n" +
	"\tAuthLevel\x12\x1a\n" +
	"\x16AUTH_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUTH_LEVEL_PUBLIC\x10\x01\x12\x1c\n" +
	"\x18AUTH_LEVEL_AUTHENTICATED\x10\x02\x12\x17\n" +
	"\x13AUTH_LEVEL_INTERNAL\x10\x03:N\n" +
	"\x13authz_proto_version\x12\x1c.google.protobuf.FileOptions\x18҆\x03 \x01(\rR\x11authzProtoVersion:W\n" +
	"\vauth_policy\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x14.authz.v1.AuthPolicyR\n" +
	"authPolicy:g\n" +
	"\x13service_auth_policy\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\v2\x14.authz.v1.AuthPolicyR\x11serviceAuthPolicyB@\x90\xb5\x18\x01Z:github.com/pj-hoakari/protoc-gen-authz-go/authz/v1;authzv1b\x06proto3"

var (
	file_authz_v1_options_proto_rawDescOnce sync.Once
	file_authz_v1_options_proto_rawDescData []byte
)

func file_authz_v1_options_proto_rawDescGZIP() []byte {
	file_authz_v1_options_proto_rawDescOnce.Do(func() {
		file_authz_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authz_v1_options_proto_rawDesc), len(file_authz_v1_options_proto_rawDesc)))
	})
	return file_authz_v1_options_proto_rawDescData
}

var file_authz_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authz_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authz_v1_options_proto_goTypes = []any{
	(AuthLevel)(0),                      // 0: authz.v1.AuthLevel
	(*AuthPolicy)(nil),                  // 1: authz.v1.AuthPolicy
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
}
var file_authz_v1_options_proto_depIdxs = []int32{
	0, // 0: authz.v1.AuthPolicy.level:type_name -> authz.v1.AuthLevel
	2, // 1: authz.v1.authz_proto_version:extendee -> google.protobuf.FileOptions
	3, // 2: authz.v1.auth_policy:extendee -> google.protobuf.MethodOptions
	4, // 3: authz.v1.service_auth_policy:extendee -> google.protobuf.ServiceOptions
	1, // 4: authz.v1.auth_policy:type_name -> authz.v1.AuthPolicy
	1, // 5: authz.v1.service_auth_policy:type_name -> authz.v1.AuthPolicy
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authz_v1_options_proto_init() }
func file_authz_v1_options_proto_init() {
	if File_authz_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authz_v1_options_proto_rawDesc), len(file_authz_v1_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_authz_v1_options_proto_goTypes,
		DependencyIndexes: file_authz_v1_options_proto_depIdxs,
		EnumInfos:         file_authz_v1_options_proto_enumTypes,
		MessageInfos:      file_authz_v1_options_proto_msgTypes,
		ExtensionInfos:    file_authz_v1_options_proto_extTypes,
	}.Build()
	File_authz_v1_options_proto = out.File
	file_authz_v1_options_proto_goTypes = nil
	file_authz_v1_options_proto_depIdxs = nil
}
