// Package generator implements protoc-gen-authz-go.
package generator

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
)

const (
	authLevelFieldNumber = protowire.Number(50001)
	unspecified          = 0
	public               = 1
	authenticated        = 2
	internal             = 3
)

// Generate writes one companion package for every generated proto file that
// declares at least one service. The companion package intentionally matches
// protoc-gen-connect-go's <go_package basename>connect convention.
func Generate(plugin *protogen.Plugin) error {
	for _, file := range plugin.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		if err := generateFile(plugin, file); err != nil {
			return err
		}
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	base := path.Base(file.GeneratedFilenamePrefix)
	dir := path.Dir(file.GeneratedFilenamePrefix)
	packageName := string(file.GoPackageName) + "connect"
	filename := path.Join(dir, packageName, base+".authz.connect.go")
	connectImportPath := protogen.GoImportPath(string(file.GoImportPath) + "connect")
	g := plugin.NewGeneratedFile(filename, connectImportPath)
	imports := newImports(g)

	g.P("// Code generated by protoc-gen-authz-go. DO NOT EDIT.")
	g.P()
	g.P("package ", packageName)
	g.P()
	g.P("// AuthLevel is the effective authorization policy of an RPC.")
	g.P("type AuthLevel int")
	g.P()
	g.P("const (")
	g.P("\tAuthLevelPublic AuthLevel = ", public)
	g.P("\tAuthLevelAuthenticated AuthLevel = ", authenticated)
	g.P("\tAuthLevelInternal AuthLevel = ", internal)
	g.P(")")
	g.P()
	g.P("// Verifier verifies that ctx satisfies level. It should return a Connect error")
	g.P("// when a particular status code is required.")
	g.P("type Verifier interface {")
	g.P("\tVerify(", imports.context("Context"), ", AuthLevel) error")
	g.P("}")
	g.P()
	g.P("// VerifierFunc adapts a function to Verifier.")
	g.P("type VerifierFunc func(", imports.context("Context"), ", AuthLevel) error")
	g.P()
	g.P("func (f VerifierFunc) Verify(ctx ", imports.context("Context"), ", level AuthLevel) error { return f(ctx, level) }")

	for _, service := range file.Services {
		generateService(g, imports, service)
	}
	return nil
}

type imports struct {
	g *protogen.GeneratedFile
}

func newImports(g *protogen.GeneratedFile) imports {
	return imports{g: g}
}

func (i imports) context(name string) string { return i.ident("context", name) }
func (i imports) errors(name string) string  { return i.ident("errors", name) }
func (i imports) fmt(name string) string     { return i.ident("fmt", name) }
func (i imports) http(name string) string    { return i.ident("net/http", name) }
func (i imports) connect(name string) string { return i.ident("connectrpc.com/connect", name) }

func (i imports) ident(path, name string) string {
	return i.g.QualifiedGoIdent(protogen.GoIdent{GoName: name, GoImportPath: protogen.GoImportPath(path)})
}

func generateService(g *protogen.GeneratedFile, imports imports, service *protogen.Service) {
	serviceName := service.GoName
	typeName := unexport(serviceName) + "AuthzInterceptor"
	g.P()
	g.P("// New", serviceName, "AuthzInterceptor creates the authorization interceptor for ", service.Desc.FullName(), ".")
	g.P("func New", serviceName, "AuthzInterceptor(verifier Verifier) ", imports.connect("Interceptor"), " {")
	g.P("\tif verifier == nil {")
	g.P("\t\tpanic(\"authz: nil verifier\")")
	g.P("\t}")
	g.P("\treturn &", typeName, "{verifier: verifier}")
	g.P("}")
	g.P()
	g.P("type ", typeName, " struct { verifier Verifier }")
	g.P()
	g.P("func (i *", typeName, ") verify(ctx ", imports.context("Context"), ", procedure string) error {")
	g.P("\tswitch procedure {")
	for _, method := range service.Methods {
		g.P("\tcase ", fmt.Sprintf("%q", procedure(service, method)), ":")
		if methodAuthLevel(method) == public {
			g.P("\t\treturn nil")
			continue
		}
		g.P("\t\tif err := i.verifier.Verify(ctx, ", levelName(methodAuthLevel(method)), "); err != nil {")
		g.P("\t\t\tvar connectErr *", imports.connect("Error"))
		g.P("\t\t\tif ", imports.errors("As"), "(err, &connectErr) { return err }")
		g.P("\t\t\treturn ", imports.connect("NewError"), "(", imports.connect("CodeUnauthenticated"), ", err)")
		g.P("\t\t}")
		g.P("\t\treturn nil")
	}
	g.P("\tdefault:")
	g.P("\t\treturn ", imports.connect("NewError"), "(", imports.connect("CodeInternal"), ", ", imports.fmt("Errorf"), "(\"authz: unknown procedure %q\", procedure))")
	g.P("\t}")
	g.P("}")
	g.P()
	g.P("func (i *", typeName, ") WrapUnary(next ", imports.connect("UnaryFunc"), ") ", imports.connect("UnaryFunc"), " {")
	g.P("\treturn func(ctx ", imports.context("Context"), ", req ", imports.connect("AnyRequest"), ") (", imports.connect("AnyResponse"), ", error) {")
	g.P("\t\tif err := i.verify(ctx, req.Spec().Procedure); err != nil { return nil, err }")
	g.P("\t\treturn next(ctx, req)")
	g.P("\t}")
	g.P("}")
	g.P()
	g.P("func (i *", typeName, ") WrapStreamingClient(next ", imports.connect("StreamingClientFunc"), ") ", imports.connect("StreamingClientFunc"), " { return next }")
	g.P()
	g.P("func (i *", typeName, ") WrapStreamingHandler(next ", imports.connect("StreamingHandlerFunc"), ") ", imports.connect("StreamingHandlerFunc"), " {")
	g.P("\treturn func(ctx ", imports.context("Context"), ", conn ", imports.connect("StreamingHandlerConn"), ") error {")
	g.P("\t\tif err := i.verify(ctx, conn.Spec().Procedure); err != nil { return err }")
	g.P("\t\treturn next(ctx, conn)")
	g.P("\t}")
	g.P("}")
	g.P()
	g.P("// New", serviceName, "HandlerWithAuthz injects the generated authorization interceptor into the Connect handler.")
	g.P("func New", serviceName, "HandlerWithAuthz(svc ", serviceName, "Handler, verifier Verifier, opts ...", imports.connect("HandlerOption"), ") (string, ", imports.http("Handler"), ") {")
	g.P("\topts = append([]", imports.connect("HandlerOption"), "{", imports.connect("WithInterceptors"), "(New", serviceName, "AuthzInterceptor(verifier))}, opts...)")
	g.P("\treturn New", serviceName, "Handler(svc, opts...)")
	g.P("}")
}

func procedure(service *protogen.Service, method *protogen.Method) string {
	return "/" + string(service.Desc.FullName()) + "/" + string(method.Desc.Name())
}

func unexport(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func methodAuthLevel(method *protogen.Method) int {
	unknown := method.Desc.Options().ProtoReflect().GetUnknown()
	for len(unknown) > 0 {
		number, typ, n := protowire.ConsumeTag(unknown)
		if n < 0 {
			return authenticated
		}
		unknown = unknown[n:]
		m := protowire.ConsumeFieldValue(number, typ, unknown)
		if m < 0 {
			return authenticated
		}
		value := unknown[:m]
		unknown = unknown[m:]
		if number != authLevelFieldNumber || typ != protowire.VarintType {
			continue
		}
		level, n := protowire.ConsumeVarint(value)
		if n < 0 {
			return authenticated
		}
		switch int(level) {
		case public, authenticated, internal:
			return int(level)
		default:
			return authenticated
		}
	}
	return authenticated
}

func levelName(level int) string {
	switch level {
	case public:
		return "AuthLevelPublic"
	case internal:
		return "AuthLevelInternal"
	default:
		return "AuthLevelAuthenticated"
	}
}
