// Package generator implements protoc-gen-authz-go.
package generator

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
)

const (
	authPolicyFieldNumber  = protowire.Number(50001)
	authzProtoVersionField = protowire.Number(50002)
	supportedProtoVersion  = 2
	authzProtoFilename     = "authz/v1/options.proto"
	authzImportPath        = protogen.GoImportPath("github.com/pj-hoakari/protoc-gen-authz-go/authz")
	unspecified            = 0
	public                 = 1
	authenticated          = 2
	internal               = 3
)

// SupportedProtoVersion returns the authz option schema version understood by
// this plugin.
func SupportedProtoVersion() int { return supportedProtoVersion }

// Generate writes one companion package for every generated proto file that
// declares at least one service. The companion package intentionally matches
// protoc-gen-connect-go's <go_package basename>connect convention.
func Generate(plugin *protogen.Plugin) error {
	if err := validateAuthzProtoVersion(plugin); err != nil {
		return err
	}
	for _, file := range plugin.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		for _, service := range file.Services {
			for _, method := range service.Methods {
				policy := authPolicyForMethod(service, method)
				if policy.level != public {
					continue
				}
				if len(policy.requiredScopes) > 0 {
					return fmt.Errorf("%s: PUBLIC RPCs must not declare required_scopes", method.Desc.FullName())
				}
				if len(policy.tokenUses) > 0 {
					return fmt.Errorf("%s: PUBLIC RPCs must not declare token_uses", method.Desc.FullName())
				}
			}
		}
		if err := generateFile(plugin, file); err != nil {
			return err
		}
	}
	return nil
}

// validateAuthzProtoVersion ensures that a schema copied into a consumer's
// repository is compatible with the version understood by this plugin.
func validateAuthzProtoVersion(plugin *protogen.Plugin) error {
	for _, file := range plugin.Files {
		if file.Desc.Path() != authzProtoFilename {
			continue
		}
		version, ok := authzProtoVersion(file.Desc.Options().ProtoReflect().GetUnknown())
		if !ok {
			return fmt.Errorf("%s: missing authz_proto_version; expected version %d", authzProtoFilename, supportedProtoVersion)
		}
		if version != supportedProtoVersion {
			return fmt.Errorf("%s: version %d is incompatible with protoc-gen-authz-go (expected %d)", authzProtoFilename, version, supportedProtoVersion)
		}
	}
	return nil
}

func authzProtoVersion(unknown []byte) (uint64, bool) {
	for len(unknown) > 0 {
		number, typ, n := protowire.ConsumeTag(unknown)
		if n < 0 {
			return 0, false
		}
		unknown = unknown[n:]
		m := protowire.ConsumeFieldValue(number, typ, unknown)
		if m < 0 {
			return 0, false
		}
		value := unknown[:m]
		unknown = unknown[m:]
		if number != authzProtoVersionField || typ != protowire.VarintType {
			continue
		}
		version, n := protowire.ConsumeVarint(value)
		if n < 0 {
			return 0, false
		}
		return version, true
	}
	return 0, false
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	base := path.Base(file.GeneratedFilenamePrefix)
	dir := path.Dir(file.GeneratedFilenamePrefix)
	packageName := string(file.GoPackageName) + "connect"
	filename := path.Join(dir, packageName, base+".authz.connect.go")
	connectImportPath := protogen.GoImportPath(string(file.GoImportPath) + "connect")
	g := plugin.NewGeneratedFile(filename, connectImportPath)

	g.P("// Code generated by protoc-gen-authz-go. DO NOT EDIT.")
	g.P()
	g.P("package ", packageName)

	for _, service := range file.Services {
		generateService(g, service)
	}
	return nil
}

// authzIdent qualifies a name of the shared runtime package. protogen adds the
// import only when a name is actually referenced.
func authzIdent(g *protogen.GeneratedFile, name string) string {
	return g.QualifiedGoIdent(protogen.GoIdent{GoName: name, GoImportPath: authzImportPath})
}

// generateService writes the policy table of one service. Procedure keys are
// the constants protoc-gen-connect-go generates into the same package, so a
// renamed RPC breaks the build instead of silently losing its policy.
func generateService(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName
	g.P()
	g.P("// ", serviceName, "Policies is the effective policy of every procedure of ", service.Desc.FullName(), ".")
	g.P("var ", serviceName, "Policies = ", authzIdent(g, "Policies"), "{")
	for _, method := range service.Methods {
		policy := authPolicyForMethod(service, method)
		g.P("\t", serviceName, method.GoName, "Procedure: ", policyLiteral(g, policy), ",")
	}
	g.P("}")
}

type authPolicy struct {
	level          int
	requiredScopes []string
	tokenUses      []string
}

func defaultAuthPolicy() authPolicy { return authPolicy{level: authenticated} }

// authPolicyForMethod resolves policy in order: method, service, then the
// fail-closed default. An explicitly unspecified policy is considered set and
// therefore resolves to the fail-closed default rather than inheriting.
func authPolicyForMethod(service *protogen.Service, method *protogen.Method) authPolicy {
	if policy, ok := authPolicyFromUnknown(method.Desc.Options().ProtoReflect().GetUnknown()); ok {
		return policy
	}
	if policy, ok := authPolicyFromUnknown(service.Desc.Options().ProtoReflect().GetUnknown()); ok {
		return policy
	}
	return defaultAuthPolicy()
}

// authPolicyFromUnknown returns whether an auth_policy extension was present.
func authPolicyFromUnknown(unknown []byte) (authPolicy, bool) {
	policy := defaultAuthPolicy()
	found := false
	for len(unknown) > 0 {
		number, typ, n := protowire.ConsumeTag(unknown)
		if n < 0 {
			return defaultAuthPolicy(), false
		}
		unknown = unknown[n:]
		m := protowire.ConsumeFieldValue(number, typ, unknown)
		if m < 0 {
			return defaultAuthPolicy(), false
		}
		value := unknown[:m]
		unknown = unknown[m:]
		if number != authPolicyFieldNumber || typ != protowire.BytesType {
			continue
		}
		found = true
		decoded, ok := decodeAuthPolicy(value, policy)
		if !ok {
			return defaultAuthPolicy(), true
		}
		policy = decoded
	}
	return policy, found
}

func decodeAuthPolicy(value []byte, policy authPolicy) (authPolicy, bool) {
	message, n := protowire.ConsumeBytes(value)
	if n < 0 {
		return defaultAuthPolicy(), false
	}
	for len(message) > 0 {
		number, typ, n := protowire.ConsumeTag(message)
		if n < 0 {
			return defaultAuthPolicy(), false
		}
		message = message[n:]
		m := protowire.ConsumeFieldValue(number, typ, message)
		if m < 0 {
			return defaultAuthPolicy(), false
		}
		field := message[:m]
		message = message[m:]
		switch {
		case number == 1 && typ == protowire.VarintType:
			level, n := protowire.ConsumeVarint(field)
			if n < 0 {
				return defaultAuthPolicy(), false
			}
			switch int(level) {
			case public, authenticated, internal:
				policy.level = int(level)
			default:
				policy.level = authenticated
			}
		case number == 2 && typ == protowire.BytesType:
			scope, n := protowire.ConsumeString(field)
			if n < 0 {
				return defaultAuthPolicy(), false
			}
			policy.requiredScopes = append(policy.requiredScopes, scope)
		case number == 3 && typ == protowire.BytesType:
			tokenUse, n := protowire.ConsumeString(field)
			if n < 0 {
				return defaultAuthPolicy(), false
			}
			policy.tokenUses = append(policy.tokenUses, tokenUse)
		}
	}
	return policy, true
}

// policyLiteral writes the value of a table entry. The composite literal type
// is elided, and empty lists are left out entirely.
func policyLiteral(g *protogen.GeneratedFile, policy authPolicy) string {
	var b strings.Builder
	b.WriteString("{Level: ")
	b.WriteString(authzIdent(g, levelName(policy.level)))
	writeStringSlice(&b, "RequiredScopes", policy.requiredScopes)
	writeStringSlice(&b, "TokenUses", policy.tokenUses)
	b.WriteString("}")
	return b.String()
}

func writeStringSlice(b *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		return
	}
	b.WriteString(", ")
	b.WriteString(field)
	b.WriteString(": []string{")
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(fmt.Sprintf("%q", value))
	}
	b.WriteString("}")
}

func levelName(level int) string {
	switch level {
	case public:
		return "LevelPublic"
	case internal:
		return "LevelInternal"
	default:
		return "LevelAuthenticated"
	}
}
